name: 'PR Semver Bump'
description: 'Bump and tag a new version using pull request metadata'
inputs:
  mode:
    description: The mode in which to run this action ('validate' or 'bump')
    required: true
  major-label:
    description: The name of the PR label that specifies a major release
    required: false
    default: 'major release'
  minor-label:
    description: The name of the PR label that specifies a minor release
    required: false
    default: 'minor release'
  patch-label:
    description: The name of the PR label that specifies a patch release
    required: false
    default: 'patch release'
  noop-labels:
    description: The name of PR labels that specify a skipped release
    required: false
    default: ''
  require-release-notes:
    description: Whether or not release notes are required
    required: false
    default: 'false'
  release-notes-prefix:
    description: Text that designates the start of the release notes
    required: false
    default: ''
  release-notes-suffix:
    description: Text that designates the end of the release notes
    required: false
    default: ''
  repo-token:
    description: The repository's GITHUB_TOKEN, used to obtain PR data
    required: true
  with-v:
    description: Set to 'true' to prefix versions with 'v'
    required: false
    default: 'false'
  base-branch:
    description: Set to 'true' to only consider version tags on the PR base branch. By default considers all version tags in the repository.
    required: false
    default: 'false'
outputs:
  old-version:
    description: The version tag prior to bumping
  version:
    description: The version tag after bumping
  release-notes:
    description: The version's release notes
  skipped:
    description: Indicator if the new version is skipped
runs:
  using: 'node20'
  main: 'dist/index.js'
