name: Master CI
on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  bump-version:
    name: Tag New Release Version
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: Bump and Tag New Release Version
        with:
          mode: bump
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          require-release-notes: true
          major-label: "SemVer:major"
          minor-label: "SemVer:minor"
          patch-label: "SemVer:patch"
          skip-label: "SemVer:none"
          with-v: true
